name: "Compile and Test"

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  all:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        name: "Clone the repository"
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21.6"
        name: "Set up Golang"
      - run: "make vendor"
        name: Download dependencies
      - run: "make test"
        name: "Run unit tests"
